In [1]:
import pandas as pd
from zipfile import ZipFile
import seaborn as sns 
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
# Opening the zip file and extracting the dataset
ZipFile("pd_nibrs_datasd.zip").extractall()

# Read the dataset into a DataFrame
df = pd.read_csv('pd_nibrs_datasd.csv', low_memory=False)

# Create a new DataFrame keeping only the relevant data
data = df[['case_number', 'occured_on', 'code_section', 'pd_offense_category',
                'neighborhood', 'division', 'block_addr', 'city', 'zip', 'latitude', 'longitude']]

In [3]:
data.head()

,case_number,occured_on,code_section,pd_offense_category,neighborhood,division,block_addr,city,zip,latitude,longitude
0,21032576,2021-07-11 20:45:00,148 (A)(1) PC OBSTRUCT/RESIST PEACE OFCR/EMER ...,All Other Offenses,Stockton,Central,100 31st ST,SAN DIEGO,92102.0,32.706474,-117.127455
1,22701933,2022-02-11 22:00:00,459 PC BURGLARY (VEHICLE) (F) ||,Theft From Motor Vehicle,Mira Mesa,Northeastern,10000 MAYA LINDA ROAD,SAN DIEGO,92126.0,32.901073,-117.120120
2,21020993,2021-05-02 06:00:00,273.5 (A) PC SPOUSAL/COHABITANT ABUSE WITH MIN...,Simple Assault,Midway District,Western,3800 Greenwood ST,SAN DIEGO,92110.0,32.754899,-117.206022
3,22041849,2022-09-21 12:46:21,273 A (A) PC WILLFUL CRUELTY TO CHILD: WITH IN...,Aggravated Assault,Unknown,Unknown,NaN,NaN,92254.0,NaN,NaN
4,21001415,2021-01-09 11:23:00,10851 (A) VC OTHER AGENCY VEHICLE THEFT/RECOVE...,Stolen Property Offenses,Egger Highlands,Southern,1100 Walnut AVE,CHULA VISTA,91911.0,32.605965,-117.088752

In [4]:
# Display basic info about the DataFrame
print("DataFrame Info:")
data.info()

# Checking for missing values in each column
print("\nMissing values in each column:")
print(data.isnull().sum())

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432566 entries, 0 to 432565
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   case_number          432566 non-null  object
 1   occured_on           432566 non-null  object
 2   code_section         432560 non-null  object
 3   pd_offense_category  432566 non-null  object
 4   neighborhood         432562 non-null  object
 5   division             432560 non-null  object
 6   block_addr           401453 non-null  object
 7   city                 423900 non-null  object
 8   zip                  429326 non-null  float64
 9   latitude             422616 non-null  float64
 10  longitude            422616 non-null  float64
dtypes: float64(3), object(8)
memory usage: 36.3+ MB

Missing values in each column:
case_number                0
occured_on                 0
code_section               6
pd_offense_category        0
neighborhood               4
division                   6
block_addr             31113
city                    8666
zip                     3240
latitude                9950
longitude               9950
dtype: int64

In [5]:
# Convert 'occurred_on' to datetime format and extract date components in one go
data['occurred_on'] = pd.to_datetime(data['occured_on'], errors='coerce')

# Extract year, month, day of week, day, hour, and minute
data[['year', 'month', 'day_of_week', 'day', 'hour', 'minute']] = data['occurred_on'].apply(
    lambda x: pd.Series([x.year, x.month, x.dayofweek, x.day, x.hour, x.minute] if pd.notnull(x) else [None]*6)
)

# Drop the original 'occured_on' column
data = data.drop(columns=['occured_on'])

C:\Users\sarah\AppData\Local\Temp\ipykernel_2508\2249926391.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['occurred_on'] = pd.to_datetime(data['occured_on'], errors='coerce')
C:\Users\sarah\AppData\Local\Temp\ipykernel_2508\2249926391.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['year', 'month', 'day_of_week', 'day', 'hour', 'minute']] = data['occurred_on'].apply(
C:\Users\sarah\AppData\Local\Temp\ipykernel_2508\2249926391.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['year', 'month', 'day_of_week', 'day', 'hour', 'minute']] = data['occurred_on'].apply(
C:\Users\sarah\AppData\Local\Temp\ipykernel_2508\2249926391.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['year', 'month', 'day_of_week', 'day', 'hour', 'minute']] = data['occurred_on'].apply(
C:\Users\sarah\AppData\Local\Temp\ipykernel_2508\2249926391.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['year', 'month', 'day_of_week', 'day', 'hour', 'minute']] = data['occurred_on'].apply(
C:\Users\sarah\AppData\Local\Temp\ipykernel_2508\2249926391.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['year', 'month', 'day_of_week', 'day', 'hour', 'minute']] = data['occurred_on'].apply(
C:\Users\sarah\AppData\Local\Temp\ipykernel_2508\2249926391.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[['year', 'month', 'day_of_week', 'day', 'hour', 'minute']] = data['occurred_on'].apply(

In [6]:
# Fill NaN values with a placeholder, for example, '0'
data['zip'] = data['zip'].fillna(0).astype(int).astype(str)

In [7]:
# Drop rows that still have missing values in 'latitude' or 'longitude'
data = data.dropna(subset=['latitude', 'longitude'])

In [8]:
# Remove trailing '||' from code_section
data['code_section'] = data['code_section'].str.replace(r' \|\| $', '', regex=True)

In [10]:
# Make block_addr title case
data['block_addr'] = data['block_addr'].str.title()

In [12]:
# Display basic info about the DataFrame
print("DataFrame Info:")
data.info()

# Checking for missing values in each column
print("\nMissing values in each column:")
print(data.isnull().sum())

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 422616 entries, 0 to 432565
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   case_number          422616 non-null  object
 1   code_section         422611 non-null  object
 2   pd_offense_category  422616 non-null  object
 3   neighborhood         422613 non-null  object
 4   division             422611 non-null  object
 5   block_addr           399617 non-null  object
 6   city                 422604 non-null  object
 7   zip                  422616 non-null  object
 8   latitude             422616 non-null  float64
 9   longitude            422616 non-null  float64
 10  occurred_on          422616 non-null  datetime64[ns]
 11  year                 422616 non-null  int64
 12  month                422616 non-null  int64
 13  day_of_week          422616 non-null  int64
 14  day                  422616 non-null  int64
 15  hour                 422616 non-null  int64
 16  minute               422616 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(6), object(8)
memory usage: 58.0+ MB

Missing values in each column:
case_number                0
code_section               5
pd_offense_category        0
neighborhood               3
division                   5
block_addr             22999
city                      12
zip                        0
latitude                   0
longitude                  0
occurred_on                0
year                       0
month                      0
day_of_week                0
day                        0
hour                       0
minute                     0
dtype: int64

In [13]:
data.head()

,case_number,code_section,pd_offense_category,neighborhood,division,block_addr,city,zip,latitude,longitude,occurred_on,year,month,day_of_week,day,hour,minute
0,21032576,148 (A)(1) PC OBSTRUCT/RESIST PEACE OFCR/EMER ...,All Other Offenses,Stockton,Central,100 31St St,SAN DIEGO,92102,32.706474,-117.127455,2021-07-11 20:45:00,2021,7,6,11,20,45
1,22701933,459 PC BURGLARY (VEHICLE) (F),Theft From Motor Vehicle,Mira Mesa,Northeastern,10000 Maya Linda Road,SAN DIEGO,92126,32.901073,-117.120120,2022-02-11 22:00:00,2022,2,4,11,22,0
2,21020993,273.5 (A) PC SPOUSAL/COHABITANT ABUSE WITH MIN...,Simple Assault,Midway District,Western,3800 Greenwood St,SAN DIEGO,92110,32.754899,-117.206022,2021-05-02 06:00:00,2021,5,6,2,6,0
4,21001415,10851 (A) VC OTHER AGENCY VEHICLE THEFT/RECOVE...,Stolen Property Offenses,Egger Highlands,Southern,1100 Walnut Ave,CHULA VISTA,91911,32.605965,-117.088752,2021-01-09 11:23:00,2021,1,5,9,11,23
5,23009256,10851 (A) VC TAKE VEHICLE W/O OWNER'S CONSENT/...,Motor Vehicle Theft,Rolando,Mid-City,4500 Mataro Dr,SAN DIEGO,92115,32.759579,-117.055797,2023-03-04 01:04:00,2023,3,5,4,1,4

In [15]:
# Export the cleaned data to a new CSV
data.to_csv('cleaned_crime_data.csv', index=False)

# Check the result
print("Data has been cleaned and saved as 'cleaned_crime_data.csv'.")

Data has been cleaned and saved as 'cleaned_crime_data.csv'.